/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardMangaRouteImport } from './routes/_authenticated/dashboard/manga'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard/favorites'
import { Route as AuthenticatedDashboardStoriesIndexRouteImport } from './routes/_authenticated/dashboard/stories/index'
import { Route as AuthenticatedDashboardStoriesNewRouteImport } from './routes/_authenticated/dashboard/stories/new'
import { Route as AuthenticatedDashboardMangaProjectIdRouteImport } from './routes/_authenticated/dashboard/manga/$projectId'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardMangaRoute =
  AuthenticatedDashboardMangaRouteImport.update({
    id: '/dashboard/manga',
    path: '/dashboard/manga',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/dashboard/favorites',
    path: '/dashboard/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardStoriesIndexRoute =
  AuthenticatedDashboardStoriesIndexRouteImport.update({
    id: '/dashboard/stories/',
    path: '/dashboard/stories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardStoriesNewRoute =
  AuthenticatedDashboardStoriesNewRouteImport.update({
    id: '/dashboard/stories/new',
    path: '/dashboard/stories/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardMangaProjectIdRoute =
  AuthenticatedDashboardMangaProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedDashboardMangaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/manga': typeof AuthenticatedDashboardMangaRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/manga/$projectId': typeof AuthenticatedDashboardMangaProjectIdRoute
  '/dashboard/stories/new': typeof AuthenticatedDashboardStoriesNewRoute
  '/dashboard/stories/': typeof AuthenticatedDashboardStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/manga': typeof AuthenticatedDashboardMangaRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/manga/$projectId': typeof AuthenticatedDashboardMangaProjectIdRoute
  '/dashboard/stories/new': typeof AuthenticatedDashboardStoriesNewRoute
  '/dashboard/stories': typeof AuthenticatedDashboardStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/manga': typeof AuthenticatedDashboardMangaRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/manga/$projectId': typeof AuthenticatedDashboardMangaProjectIdRoute
  '/_authenticated/dashboard/stories/new': typeof AuthenticatedDashboardStoriesNewRoute
  '/_authenticated/dashboard/stories/': typeof AuthenticatedDashboardStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gallery'
    | '/dashboard/favorites'
    | '/dashboard/manga'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/manga/$projectId'
    | '/dashboard/stories/new'
    | '/dashboard/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gallery'
    | '/dashboard/favorites'
    | '/dashboard/manga'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/manga/$projectId'
    | '/dashboard/stories/new'
    | '/dashboard/stories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/gallery'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/manga'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/manga/$projectId'
    | '/_authenticated/dashboard/stories/new'
    | '/_authenticated/dashboard/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manga': {
      id: '/_authenticated/dashboard/manga'
      path: '/dashboard/manga'
      fullPath: '/dashboard/manga'
      preLoaderRoute: typeof AuthenticatedDashboardMangaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/stories/': {
      id: '/_authenticated/dashboard/stories/'
      path: '/dashboard/stories'
      fullPath: '/dashboard/stories/'
      preLoaderRoute: typeof AuthenticatedDashboardStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/stories/new': {
      id: '/_authenticated/dashboard/stories/new'
      path: '/dashboard/stories/new'
      fullPath: '/dashboard/stories/new'
      preLoaderRoute: typeof AuthenticatedDashboardStoriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manga/$projectId': {
      id: '/_authenticated/dashboard/manga/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/manga/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardMangaProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMangaRoute
    }
  }
}

interface AuthenticatedDashboardMangaRouteChildren {
  AuthenticatedDashboardMangaProjectIdRoute: typeof AuthenticatedDashboardMangaProjectIdRoute
}

const AuthenticatedDashboardMangaRouteChildren: AuthenticatedDashboardMangaRouteChildren =
  {
    AuthenticatedDashboardMangaProjectIdRoute:
      AuthenticatedDashboardMangaProjectIdRoute,
  }

const AuthenticatedDashboardMangaRouteWithChildren =
  AuthenticatedDashboardMangaRoute._addFileChildren(
    AuthenticatedDashboardMangaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardMangaRoute: typeof AuthenticatedDashboardMangaRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardStoriesNewRoute: typeof AuthenticatedDashboardStoriesNewRoute
  AuthenticatedDashboardStoriesIndexRoute: typeof AuthenticatedDashboardStoriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
  AuthenticatedDashboardMangaRoute:
    AuthenticatedDashboardMangaRouteWithChildren,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardStoriesNewRoute: AuthenticatedDashboardStoriesNewRoute,
  AuthenticatedDashboardStoriesIndexRoute:
    AuthenticatedDashboardStoriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
